dist: xenial
language: python
services:
  - docker
python:
  - "3.6"
cache:
  directories:
    - $HOME/.pip/download-cache
    - $HOME/.pip-accel
    - $HOME/.cache/pip
addons:
  apt:
    packages:
        - libevent-dev
        - shelltestrunner
        - bats
    sources:
      - sourceline: 'ppa:duggan/bats'
install:
  - wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz && rm dockerize-linux-amd64-v0.6.1.tar.gz
  - pip install -r requirements.txt
  - docker-compose build
  - git submodule add https://github.com/ztombol/bats-support tests/test_helper/bats-support
  - git submodule add https://github.com/ztombol/bats-assert tests/test_helper/bats-assert
script:
  - nosetests tests/unit
  - bats tests/integration/basic.bats
