sudo: false
language: python
services:
  - docker
python:
  - "3.6"
cache:
  apt: true
  directories:
    - $HOME/.pip/download-cache
    - $HOME/.pip-accel
    - $HOME/.cache/pip
addons:
  apt:
    packages:
        - libevent-dev
        - shelltestrunner

# command to install dependencies
install:
  - pip install -r requirements-$TRAVIS_PYTHON_VERSION.txt
  - pip install -r requirements.txt
  - docker-compose build
  - docker-compose up -d
# command to run tests
script: nosetests tests/unit
