sudo: false
language: python
services:
  - docker
python:
  - "3.6"
cache:
  directories:
    - $HOME/.pip/download-cache
    - $HOME/.pip-accel
    - $HOME/.cache/pip
addons:
  apt:
    packages:
        - libevent-dev
        - shelltestrunner
        - dockerize
# command to install dependencies
install:
  - wget https://github.com/jwilder/dockerize/releases/download/0.6.1/dockerize-linux-amd64-0.6.1.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-0.6.1.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
  - pip install -r requirements-$TRAVIS_PYTHON_VERSION.txt
  - pip install -r requirements.txt
  - docker-compose build
# command to run tests
script:
  - nosetests tests/unit
  - dockerize -wait tcp://localhost:5672 -timeout 25s echo "Waited"
