sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
cache:
  apt: true
  directories:
    - $HOME/.pip/download-cache
    - $HOME/.pip-accel
    - $HOME/.cache/pip
addons:
  apt:
    packages:
        - libevent-dev

# command to install dependencies
install:
  - pip install -r requirements-$TRAVIS_PYTHON_VERSION.txt
  - pip install -r requirements.txt
# command to run tests
script: nosetests tests/unit tests/integration
