version: '3'
services:
  dispatcher:
    build: .
    volumes:
      - .:/app
    depends_on:
      - rabbit
    environment:
      NOMAD_ALLOC_ID: 17
      NOMAD_JOB_NAME: 2000
  rabbit:
    ports:
      - "15673:15672"
    image: rabbitmq:management-alpine
